config/routes.rb
Rails.application.routes.draw do
  
root 'users#login'
get "/app/views/users/login.html.erb", to: "users#login", as: "login"
get "/app/views/mainprograms/mainpage.html.erb", to: "mainprograms#mainpage", as: "mainpage"
 
  resources :mainprograms do
  #get 'mainp/page'
    collection do
      post :mainpage
      post :jan
      post :feb
    end
  end
  
  resources :users do
    collection do
      post :logintoaccount
    end
  end
  
end

app/models/mainprogram.rb
class Mainprogram < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mainprograms_controller.rb
require 'rubygems'
require 'googlecharts'
require 'gchart'
require 'roo'
require 'roo-xls'

class MainprogramsController < ApplicationController
  before_action :set_mainprogram, only: [:show, :edit, :update, :destroy]

  $month = 'none'

  # GET /mainprograms
  # GET /mainprograms.json
  def index
    @mainprograms = Mainprogram.all
  end

  # GET /mainprograms/1
  # GET /mainprograms/1.json
  def show
  end
  
  def jan
   redirect_to mainpage_path
   $month = 'jan'
  end
  
  def feb
   redirect_to mainpage_path
   $month = 'feb'
  end
  
  def mainpage
    if $month != 'none'
      if $month == 'jan'
        @title = "January Delay Reason %"
        @exceltable = 'FlightJan.xls'
      end
      if $month == 'feb'
        @title = "Febuary Delay Reason %"
        @exceltable = 'FlightFeb.xls'
      end
      s = Roo::Excel.new(Rails.root.join('app', 'assets', @exceltable))
      s.default_sheet = s.sheets.first
      $i = 1
      $o = 1
      $k = 1
      $l = 1
      $m = 1
      $num = 21
      carrierd = 0
      weatherd = 0
      nasd = 0
      securityd = 0
      lateplaned = 0
      while $i < $num  do
        if s.cell('B',$i) != 'NA'
          carrierd = carrierd + s.cell('B',$i).to_i
        end
        $i +=1
      end
      while $o < $num  do
        if s.cell('C',$o) != 'NA'
          weatherd = weatherd + s.cell('C',$o).to_i
        end
        $o +=1
      end
      while $k < $num  do
        if s.cell('D',$k) != 'NA'
          nasd = nasd + s.cell('D',$k).to_i
        end
        $k +=1
      end
      while $l < $num  do
        if s.cell('E',$l) != 'NA'
          securityd = securityd + s.cell('E',$l).to_i
        end
        $l +=1
      end
      while $m < $num  do
        if s.cell('F',$m) != 'NA'
          lateplaned = lateplaned + s.cell('F',$m).to_i
        end
        $m +=1
      end
      @pie_chart = Gchart.pie_3d(:title => @title, :labels => ['Carrier', 'Weather', 'NAS', 'Security', 'Late Plane',], :data => [carrierd, weatherd, nasd, securityd, lateplaned], :size => '400x200')
    end
  end

  # GET /mainprograms/new
  def new
    @mainprogram = Mainprogram.new
  end

  # GET /mainprograms/1/edit
  def edit
  end

  # POST /mainprograms
  # POST /mainprograms.json
  def create
    @mainprogram = Mainprogram.new(mainprogram_params)

    respond_to do |format|
      if @mainprogram.save
        format.html { redirect_to @mainprogram, notice: 'Mainprogram was successfully created.' }
        format.json { render :show, status: :created, location: @mainprogram }
      else
        format.html { render :new }
        format.json { render json: @mainprogram.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mainprograms/1
  # PATCH/PUT /mainprograms/1.json
  def update
    respond_to do |format|
      if @mainprogram.update(mainprogram_params)
        format.html { redirect_to @mainprogram, notice: 'Mainprogram was successfully updated.' }
        format.json { render :show, status: :ok, location: @mainprogram }
      else
        format.html { render :edit }
        format.json { render json: @mainprogram.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mainprograms/1
  # DELETE /mainprograms/1.json
  def destroy
    @mainprogram.destroy
    respond_to do |format|
      format.html { redirect_to mainprograms_url, notice: 'Mainprogram was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mainprogram
      @mainprogram = Mainprogram.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mainprogram_params
      params.fetch(:mainprogram, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def login
  end
  
  # GET /users/1
  # GET /users/1.json
  def show
  end
  
  def logintoaccount
   redirect_to mainpage_path
  end
  
  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mainprograms_helper.rb
module MainprogramsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mainprograms/_form.html.erb
<%= form_for(@mainprogram) do |f| %>
  <% if @mainprogram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mainprogram.errors.count, "error") %> prohibited this mainprogram from being saved:</h2>

      <ul>
      <% @mainprogram.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mainprograms/edit.html.erb
<h1>Editing Mainprogram</h1>

<%= render 'form' %>

<%= link_to 'Show', @mainprogram %> |
<%= link_to 'Back', mainprograms_path %>

app/views/mainprograms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mainprograms</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mainprograms.each do |mainprogram| %>
      <tr>
        <td><%= link_to 'Show', mainprogram %></td>
        <td><%= link_to 'Edit', edit_mainprogram_path(mainprogram) %></td>
        <td><%= link_to 'Destroy', mainprogram, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mainprogram', new_mainprogram_path %>

app/views/mainprograms/mainpage.html.erb
<h1>Flight Delay Stats</h1> 
<%= link_to 'Logout', login_path %>
<p></p>
<h3>Select A Month:</h3> 
<%= button_to 'January', jan_mainprograms_url, method: :post %>
<%= button_to 'Febuary', feb_mainprograms_url, method: :post %>
<p></p>
<h3>Month Stats:</h3> 
<img src="<%= @pie_chart %>"/>
<p></p>
Carrier: Plane boarding was delayed after plane had landed<br>
Weather: Weather prevented plane takeoff/landing<br>
NAS: Delays imposed by the National Airspace System for various possible reasons<br>
Security: Security threat delayed takeoff<br>
Late Plane: Plane landed behind schedule<br>

app/views/mainprograms/new.html.erb
<h1>New Mainprogram</h1>

<%= render 'form' %>

<%= link_to 'Back', mainprograms_path %>

app/views/mainprograms/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_mainprogram_path(@mainprogram) %> |
<%= link_to 'Back', mainprograms_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :admin %><br>
    <%= f.check_box :admin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<h1>Flight Delay Stats</h1>
Username: <input type="text" name="usernamebox" value=""><br>
Password: <input type="text" name="passwordbox" value=""><br>
<%= link_to 'New User', new_user_path %><br>
<%= button_to 'Login', logintoaccount_users_url, method: :post %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>
<%= link_to 'Login', login_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>